# Generated by Django 2.2.5 on 2021-01-14 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commune', models.CharField(max_length=45)),
                ('distance_agence', models.FloatField()),
                ('nbre_habitant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeLogement',
            fields=[
                ('type_logement', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('charges_forfaitaires', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_quartier', models.CharField(max_length=35)),
                ('id_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logement.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=5)),
                ('rue', models.CharField(max_length=60)),
                ('superficie', models.FloatField()),
                ('loyer', models.FloatField()),
                ('id_quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logement.Quartier')),
                ('type_logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logement.TypeLogement')),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=35)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('num_telephone', models.CharField(max_length=12)),
                ('num_logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logement.Logement')),
            ],
        ),
    ]
